// Code generated by protoc-gen-go-micro. DO NOT EDIT.
// protoc-gen-go-micro version: v3.4.1
// source: test.proto

package pb

import (
	context "context"
	api "github.com/unistack-org/micro/v3/api"
	client "github.com/unistack-org/micro/v3/client"
)

var (
	TestServiceName = "TestService"

	TestServiceEndpoints = []api.Endpoint{
		api.Endpoint{
			Name:    "TestService.LookupUser",
			Path:    []string{"/v1/user/lookup/{name}"},
			Method:  []string{"GET"},
			Handler: "rpc",
		},
	}
)

func NewTestServiceEndpoints() []api.Endpoint {
	return TestServiceEndpoints
}

type TestServiceClient interface {
	LookupUser(ctx context.Context, req *LookupUserReq, opts ...client.CallOption) (*LookupUserRsp, error)
}

type TestServiceServer interface {
	LookupUser(ctx context.Context, req *LookupUserReq, rsp *LookupUserRsp) error
}
