// Code generated by protoc-gen-go-micro. DO NOT EDIT.
// versions:
// - protoc-gen-go-micro v3.10.4
// - protoc              v5.29.2
// source: test.proto

package pb

import (
	context "context"
	client "go.unistack.org/micro/v3/client"
)

var (
	TestServiceName = "TestService"
)

type TestServiceClient interface {
	LookupUser(ctx context.Context, req *LookupUserReq, opts ...client.CallOption) (*LookupUserRsp, error)
	UpdateUser(ctx context.Context, req *UpdateUserReq, opts ...client.CallOption) (*UpdateUserRsp, error)
	DeleteUser(ctx context.Context, req *DeleteUserReq, opts ...client.CallOption) (*DeleteUserRsp, error)
	MailUser(ctx context.Context, req *MailUserReq, opts ...client.CallOption) (*MailUserRsp, error)
}

type TestServiceServer interface {
	LookupUser(ctx context.Context, req *LookupUserReq, rsp *LookupUserRsp) error
	UpdateUser(ctx context.Context, req *UpdateUserReq, rsp *UpdateUserRsp) error
	DeleteUser(ctx context.Context, req *DeleteUserReq, rsp *DeleteUserRsp) error
	MailUser(ctx context.Context, req *MailUserReq, rsp *MailUserRsp) error
}
