// Code generated by protoc-gen-go-micro. DO NOT EDIT.
// versions:
// - protoc-gen-go-micro v3.10.1
// - protoc              v3.21.12
// source: test.proto

package pb

import (
	context "context"
	v3 "go.unistack.org/micro-server-http/v3"
	client "go.unistack.org/micro/v3/client"
)

var (
	TestServiceName = "TestService"
)
var (
	TestServiceServerEndpoints = []v3.EndpointMetadata{
		{
			Name:   "TestService.LookupUser",
			Path:   "/v1/user/{name}",
			Method: "GET",
			Body:   "",
			Stream: false,
		},
		{
			Name:   "TestService.UpdateUser",
			Path:   "/v1/user/{name}",
			Method: "PUT",
			Body:   "*",
			Stream: false,
		},
		{
			Name:   "TestService.DeleteUser",
			Path:   "/v1/user/{name}",
			Method: "DELETE",
			Body:   "",
			Stream: false,
		},
		{
			Name:   "TestService.MailUser",
			Path:   "/v1/user/{name}/mail",
			Method: "POST",
			Body:   "*",
			Stream: false,
		},
	}
)

type TestServiceClient interface {
	LookupUser(ctx context.Context, req *LookupUserReq, opts ...client.CallOption) (*LookupUserRsp, error)
	UpdateUser(ctx context.Context, req *UpdateUserReq, opts ...client.CallOption) (*UpdateUserRsp, error)
	DeleteUser(ctx context.Context, req *DeleteUserReq, opts ...client.CallOption) (*DeleteUserRsp, error)
	MailUser(ctx context.Context, req *MailUserReq, opts ...client.CallOption) (*MailUserRsp, error)
}

type TestServiceServer interface {
	LookupUser(ctx context.Context, req *LookupUserReq, rsp *LookupUserRsp) error
	UpdateUser(ctx context.Context, req *UpdateUserReq, rsp *UpdateUserRsp) error
	DeleteUser(ctx context.Context, req *DeleteUserReq, rsp *DeleteUserRsp) error
	MailUser(ctx context.Context, req *MailUserReq, rsp *MailUserRsp) error
}
