// Code generated by protoc-gen-micro
// source: test.proto
package pb

import (
	context "context"
	api "github.com/unistack-org/micro/v3/api"
	client "github.com/unistack-org/micro/v3/client"
)

func NewTestEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

type TestClient interface {
	Call(ctx context.Context, req *Request, opts ...client.CallOption) (*Response, error)
}

type TestServer interface {
	Call(ctx context.Context, req *Request, rsp *Response) error
}
