// Code generated by protoc-gen-go-micro. DO NOT EDIT.
// protoc-gen-go-micro version: v3.5.3
// source: test.proto

package pb

import (
	context "context"
	api "go.unistack.org/micro/v3/api"
	client "go.unistack.org/micro/v3/client"
)

var (
	TestName = "Test"

	TestEndpoints = []api.Endpoint{}
)

func NewTestEndpoints() []api.Endpoint {
	return TestEndpoints
}

type TestClient interface {
	Call(ctx context.Context, req *Request, opts ...client.CallOption) (*Response, error)
}

type TestServer interface {
	Call(ctx context.Context, req *Request, rsp *Response) error
}
