// Code generated by protoc-gen-go-micro. DO NOT EDIT.
// versions:
// - protoc-gen-go-micro v3.10.4
// - protoc              v5.29.2
// source: test.proto

package pb

import (
	context "context"
	client "go.unistack.org/micro/v3/client"
)

var (
	TestName = "Test"
)

type TestClient interface {
	Call(ctx context.Context, req *Request, opts ...client.CallOption) (*Response, error)
}

type TestServer interface {
	Call(ctx context.Context, req *Request, rsp *Response) error
}
