// Code generated by protoc-gen-go-micro. DO NOT EDIT.
// protoc-gen-go-micro version: v3.4.0
// source: test.proto

package pb

import (
	context "context"
	api "github.com/unistack-org/micro/v3/api"
	client "github.com/unistack-org/micro/v3/client"
)

var (
	TestDoubleEndpoints = []api.Endpoint{
		api.Endpoint{
			Name:    "TestDouble.CallDouble",
			Path:    []string{"/v1/testdouble/call/{name}"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
	}
)

func NewTestDoubleEndpoints() []api.Endpoint {
	return TestDoubleEndpoints
}

type TestDoubleClient interface {
	CallDouble(ctx context.Context, req *CallReq, opts ...client.CallOption) (*CallRsp, error)
}

type TestDoubleServer interface {
	CallDouble(ctx context.Context, req *CallReq, rsp *CallRsp) error
}

var (
	TestEndpoints = []api.Endpoint{
		api.Endpoint{
			Name:    "Test.CallRepeatedString",
			Path:    []string{"/v1/test/call_repeated_string/{string_ids}"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
		api.Endpoint{
			Name:    "Test.CallRepeatedInt64",
			Path:    []string{"/v1/test/call_repeated_int64/{int64_ids}"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
		api.Endpoint{
			Name:    "Test.Call",
			Path:    []string{"/v1/test/call/{name}"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
		api.Endpoint{
			Name:    "Test.CallError",
			Path:    []string{"/v1/test/callerror/{name}"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
	}
)

func NewTestEndpoints() []api.Endpoint {
	return TestEndpoints
}

type TestClient interface {
	CallRepeatedString(ctx context.Context, req *CallReq, opts ...client.CallOption) (*CallRsp, error)
	CallRepeatedInt64(ctx context.Context, req *CallReq, opts ...client.CallOption) (*CallRsp, error)
	Call(ctx context.Context, req *CallReq, opts ...client.CallOption) (*CallRsp, error)
	CallError(ctx context.Context, req *CallReq1, opts ...client.CallOption) (*CallRsp1, error)
}

type TestServer interface {
	CallRepeatedString(ctx context.Context, req *CallReq, rsp *CallRsp) error
	CallRepeatedInt64(ctx context.Context, req *CallReq, rsp *CallRsp) error
	Call(ctx context.Context, req *CallReq, rsp *CallRsp) error
	CallError(ctx context.Context, req *CallReq1, rsp *CallRsp1) error
}
