// Code generated by protoc-gen-go-micro. DO NOT EDIT.
// protoc-gen-go-micro version: v3.5.3
// source: test.proto

package pb

import (
	context "context"

	api "go.unistack.org/micro/v3/api"
	client "go.unistack.org/micro/v3/client"
)

var (
	TestServiceName = "TestService"

	TestServiceEndpoints = []api.Endpoint{}
)

func NewTestServiceEndpoints() []api.Endpoint {
	return TestServiceEndpoints
}

type TestServiceClient interface {
	Call(ctx context.Context, req *CallReq, opts ...client.CallOption) (*CallRsp, error)
	Hello(ctx context.Context, req *CallReq, opts ...client.CallOption) (*CallRsp, error)
}

type TestServiceServer interface {
	Call(ctx context.Context, req *CallReq, rsp *CallRsp) error
	Hello(ctx context.Context, req *CallReq, rsp *CallRsp) error
}
