// Code generated by protoc-gen-go-micro. DO NOT EDIT.
// versions:
// - protoc-gen-go-micro v3.10.2
// - protoc              v3.21.12
// source: test.proto

package pb

import (
	context "context"
	v3 "go.unistack.org/micro-server-http/v3"
	client "go.unistack.org/micro/v3/client"
)

var (
	TestServiceName = "TestService"
)
var (
	TestServiceServerEndpoints = []v3.EndpointMetadata{}
)

type TestServiceClient interface {
	Call(ctx context.Context, req *CallReq, opts ...client.CallOption) (*CallRsp, error)
	Hello(ctx context.Context, req *CallReq, opts ...client.CallOption) (*CallRsp, error)
}

type TestServiceServer interface {
	Call(ctx context.Context, req *CallReq, rsp *CallRsp) error
	Hello(ctx context.Context, req *CallReq, rsp *CallRsp) error
}
