// Code generated by protoc-gen-go-micro. DO NOT EDIT.
// protoc-gen-go-micro version: v3.4.2
// source: test.proto

package pb

import (
	context "context"
	api "github.com/unistack-org/micro/v3/api"
	client "github.com/unistack-org/micro/v3/client"
)

var (
	TestServiceName = "TestService"

	TestServiceEndpoints = []api.Endpoint{}
)

func NewTestServiceEndpoints() []api.Endpoint {
	return TestServiceEndpoints
}

type TestServiceClient interface {
	Call(ctx context.Context, req *CallReq, opts ...client.CallOption) (*CallRsp, error)
	Hello(ctx context.Context, req *CallReq, opts ...client.CallOption) (*CallRsp, error)
}

type TestServiceServer interface {
	Call(ctx context.Context, req *CallReq, rsp *CallRsp) error
	Hello(ctx context.Context, req *CallReq, rsp *CallRsp) error
}
