// Code generated by protoc-gen-go-micro. DO NOT EDIT.
// versions:
// - protoc-gen-go-micro v3.5.3
// - protoc              v3.21.12
// source: test.proto

package pb

import (
	context "context"
	codec "go.unistack.org/micro-proto/v3/codec"
	api "go.unistack.org/micro/v3/api"
	client "go.unistack.org/micro/v3/client"
)

var (
	TestServiceName = "TestService"

	TestServiceEndpoints = []api.Endpoint{
		{
			Name:    "TestService.TestMultipart",
			Path:    []string{"/users/multipart"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
		{
			Name:    "TestService.TestEndpoint",
			Path:    []string{"/users/test"},
			Method:  []string{"GET"},
			Handler: "rpc",
		},
		{
			Name:    "TestService.UserByID",
			Path:    []string{"/users/{id}"},
			Method:  []string{"GET"},
			Handler: "rpc",
		},
		{
			Name:    "TestService.UserImageByID",
			Path:    []string{"/users/{id}/image"},
			Method:  []string{"GET"},
			Handler: "rpc",
		},
		{
			Name:    "TestService.UploadFile",
			Path:    []string{"/users/image/upload"},
			Method:  []string{"POST"},
			Handler: "rpc",
		},
		{
			Name:    "TestService.KzAmlRs",
			Path:    []string{"/aml"},
			Method:  []string{"POST"},
			Handler: "rpc",
		},
	}
)

func NewTestServiceEndpoints() []api.Endpoint {
	return TestServiceEndpoints
}

type TestServiceClient interface {
	TestMultipart(ctx context.Context, req *MultipartReq, opts ...client.CallOption) (*MultipartRsp, error)
	TestEndpoint(ctx context.Context, req *Request, opts ...client.CallOption) (*Response, error)
	UserByID(ctx context.Context, req *Request, opts ...client.CallOption) (*Response, error)
	UserImageByID(ctx context.Context, req *Request, opts ...client.CallOption) (*codec.Frame, error)
	UploadFile(ctx context.Context, req *RequestImage, opts ...client.CallOption) (*ResponseImage, error)
	KzAmlRs(ctx context.Context, req *RequestAml, opts ...client.CallOption) (*ResponseAml, error)
}

type TestServiceServer interface {
	TestMultipart(ctx context.Context, req *MultipartReq, rsp *MultipartRsp) error
	TestEndpoint(ctx context.Context, req *Request, rsp *Response) error
	UserByID(ctx context.Context, req *Request, rsp *Response) error
	UserImageByID(ctx context.Context, req *Request, rsp *codec.Frame) error
	UploadFile(ctx context.Context, req *RequestImage, rsp *ResponseImage) error
	KzAmlRs(ctx context.Context, req *RequestAml, rsp *ResponseAml) error
}
