// Code generated by protoc-gen-go-micro. DO NOT EDIT.
// versions:
// - protoc-gen-go-micro v3.10.4
// - protoc              v5.28.3
// source: test.proto

package pb

import (
	context "context"
	codec "go.unistack.org/micro-proto/v3/codec"
	client "go.unistack.org/micro/v3/client"
)

var (
	TestServiceName = "TestService"
)

type TestServiceClient interface {
	TestMultipart(ctx context.Context, req *MultipartReq, opts ...client.CallOption) (*MultipartRsp, error)
	TestEndpoint(ctx context.Context, req *Request, opts ...client.CallOption) (*Response, error)
	UserByID(ctx context.Context, req *Request, opts ...client.CallOption) (*Response, error)
	UserImageByID(ctx context.Context, req *Request, opts ...client.CallOption) (*codec.Frame, error)
	UploadFile(ctx context.Context, req *RequestImage, opts ...client.CallOption) (*ResponseImage, error)
	KzAmlRs(ctx context.Context, req *RequestAml, opts ...client.CallOption) (*ResponseAml, error)
}

type TestServiceServer interface {
	TestMultipart(ctx context.Context, req *MultipartReq, rsp *MultipartRsp) error
	TestEndpoint(ctx context.Context, req *Request, rsp *Response) error
	UserByID(ctx context.Context, req *Request, rsp *Response) error
	UserImageByID(ctx context.Context, req *Request, rsp *codec.Frame) error
	UploadFile(ctx context.Context, req *RequestImage, rsp *ResponseImage) error
	KzAmlRs(ctx context.Context, req *RequestAml, rsp *ResponseAml) error
}
