// Code generated by protoc-gen-go-micro. DO NOT EDIT.
// protoc-gen-go-micro version: v3.5.3
// source: test.proto

package helloworld

import (
	context "context"
	proto "go.unistack.org/micro-tests/server/grpc/proto"
	api "go.unistack.org/micro/v3/api"
	client "go.unistack.org/micro/v3/client"
)

var (
	TestName = "Test"

	TestEndpoints = []api.Endpoint{
		{
			Name:    "Test.Call",
			Path:    []string{"/api/v0/test/call/TEST"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
	}
)

func NewTestEndpoints() []api.Endpoint {
	return TestEndpoints
}

type TestClient interface {
	Call(ctx context.Context, req *proto.Request, opts ...client.CallOption) (*proto.Response, error)
}

type TestServer interface {
	Call(ctx context.Context, req *proto.Request, rsp *proto.Response) error
}
