// Code generated by protoc-gen-go-micro. DO NOT EDIT.
// versions:
// - protoc-gen-go-micro v3.10.2
// - protoc              v3.21.12
// source: test.proto

package helloworld

import (
	context "context"
	v3 "go.unistack.org/micro-server-http/v3"
	proto "go.unistack.org/micro-tests/server/grpc/proto"
	client "go.unistack.org/micro/v3/client"
)

var (
	TestName = "Test"
)
var (
	TestServerEndpoints = []v3.EndpointMetadata{
		{
			Name:   "Test.Call",
			Path:   "/api/v0/test/call/TEST",
			Method: "POST",
			Body:   "*",
			Stream: false,
		},
	}
)

type TestClient interface {
	Call(ctx context.Context, req *proto.Request, opts ...client.CallOption) (*proto.Response, error)
}

type TestServer interface {
	Call(ctx context.Context, req *proto.Request, rsp *proto.Response) error
}
