// Code generated by protoc-gen-micro
// source: test.proto
package helloworld

import (
	context "context"
	proto "github.com/unistack-org/micro-tests/server/grpc/proto"
	api "github.com/unistack-org/micro/v3/api"
	client "github.com/unistack-org/micro/v3/client"
)

func NewTestEndpoints() []*api.Endpoint {
	return []*api.Endpoint{
		&api.Endpoint{
			Name:    "Test.Call",
			Path:    []string{"/api/v0/test/call/TEST"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
	}
}

type TestClient interface {
	Call(ctx context.Context, req *proto.Request, opts ...client.CallOption) (*proto.Response, error)
}

type TestServer interface {
	Call(ctx context.Context, req *proto.Request, rsp *proto.Response) error
}
