// Code generated by protoc-gen-go-micro. DO NOT EDIT.
// versions:
// - protoc-gen-go-micro v3.10.2
// - protoc              v3.21.12
// source: proto.proto

package pb

import (
	context "context"
	v3 "go.unistack.org/micro-server-http/v3"
	proto "go.unistack.org/micro-tests/server/combo/proto"
	client "go.unistack.org/micro/v3/client"
)

var (
	TestName = "Test"
)
var (
	TestServerEndpoints = []v3.EndpointMetadata{
		{
			Name:   "Test.Call",
			Path:   "/Call",
			Method: "POST",
			Body:   "*",
			Stream: false,
		},
	}
)

type TestClient interface {
	Call(ctx context.Context, req *proto.CallReq, opts ...client.CallOption) (*proto.CallRsp, error)
}

type TestServer interface {
	Call(ctx context.Context, req *proto.CallReq, rsp *proto.CallRsp) error
}
