// Code generated by protoc-gen-go-micro. DO NOT EDIT.
// versions:
// - protoc-gen-go-micro v3.10.4
// - protoc              v5.28.3
// source: proto.proto

package pb

import (
	context "context"
	proto "go.unistack.org/micro-tests/server/combo/proto"
	client "go.unistack.org/micro/v3/client"
)

var (
	TestName = "Test"
)

type TestClient interface {
	Call(ctx context.Context, req *proto.CallReq, opts ...client.CallOption) (*proto.CallRsp, error)
}

type TestServer interface {
	Call(ctx context.Context, req *proto.CallReq, rsp *proto.CallRsp) error
}
