// Code generated by protoc-gen-go-micro. DO NOT EDIT.
// versions:
// - protoc-gen-go-micro v3.5.3
// - protoc              v3.21.12
// source: test.proto

package pb

import (
	context "context"
	proto "go.unistack.org/micro-tests/server/combo/proto"
	api "go.unistack.org/micro/v3/api"
	client "go.unistack.org/micro/v3/client"
)

var (
	TestName = "Test"

	TestEndpoints = []api.Endpoint{
		{
			Name:    "Test.Call",
			Path:    []string{"/v1/call"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
	}
)

func NewTestEndpoints() []api.Endpoint {
	return TestEndpoints
}

type TestClient interface {
	Call(ctx context.Context, req *proto.CallReq, opts ...client.CallOption) (*proto.CallRsp, error)
}

type TestServer interface {
	Call(ctx context.Context, req *proto.CallReq, rsp *proto.CallRsp) error
}
