// Code generated by protoc-gen-go-micro. DO NOT EDIT.
// protoc-gen-go-micro version: v3.4.0
// source: test.proto

package pb

import (
	context "context"
	api "github.com/unistack-org/micro/v3/api"
	client "github.com/unistack-org/micro/v3/client"
	codec "github.com/unistack-org/micro/v3/codec"
)

var (
	TestEndpoints = []api.Endpoint{}
)

func NewTestEndpoints() []api.Endpoint {
	return TestEndpoints
}

type TestClient interface {
	Call(ctx context.Context, req *codec.Frame, opts ...client.CallOption) (*codec.Frame, error)
}

type TestServer interface {
	Call(ctx context.Context, req *codec.Frame, rsp *codec.Frame) error
}
