// Code generated by protoc-gen-go-micro. DO NOT EDIT.
// versions:
// - protoc-gen-go-micro v3.10.2
// - protoc              v3.21.12
// source: test.proto

package pb

import (
	context "context"
	v3 "go.unistack.org/micro-server-http/v3"
	client "go.unistack.org/micro/v3/client"
	codec "go.unistack.org/micro/v3/codec"
)

var (
	TestName = "Test"
)
var (
	TestServerEndpoints = []v3.EndpointMetadata{}
)

type TestClient interface {
	Call(ctx context.Context, req *codec.Frame, opts ...client.CallOption) (*codec.Frame, error)
}

type TestServer interface {
	Call(ctx context.Context, req *codec.Frame, rsp *codec.Frame) error
}
