// Code generated by protoc-gen-go-micro. DO NOT EDIT.
// protoc-gen-go-micro version: v3.10.4
// source: test.proto

package pb

import (
	context "context"
	_ "go.unistack.org/micro-client-http/v3"
	v3 "go.unistack.org/micro-server-http/v3"
	client "go.unistack.org/micro/v3/client"
	codec "go.unistack.org/micro/v3/codec"
	server "go.unistack.org/micro/v3/server"
)

var (
	TestServerEndpoints = []v3.EndpointMetadata{}
)

type testClient struct {
	c    client.Client
	name string
}

func NewTestClient(name string, c client.Client) TestClient {
	return &testClient{c: c, name: name}
}

func (c *testClient) Call(ctx context.Context, req *codec.Frame, opts ...client.CallOption) (*codec.Frame, error) {
	rsp := &codec.Frame{}
	err := c.c.Call(ctx, c.c.NewRequest(c.name, "Test.Call", req), rsp, opts...)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

type testServer struct {
	TestServer
}

func (h *testServer) Call(ctx context.Context, req *codec.Frame, rsp *codec.Frame) error {
	return h.TestServer.Call(ctx, req, rsp)
}

func RegisterTestServer(s server.Server, sh TestServer, opts ...server.HandlerOption) error {
	type test interface {
		Call(ctx context.Context, req *codec.Frame, rsp *codec.Frame) error
	}
	type Test struct {
		test
	}
	h := &testServer{sh}
	var nopts []server.HandlerOption
	nopts = append(nopts, v3.HandlerEndpoints(TestServerEndpoints))
	return s.Handle(s.NewHandler(&Test{h}, append(nopts, opts...)...))
}
