// Code generated by protoc-gen-go-micro. DO NOT EDIT.
// versions:
// - protoc-gen-go-micro v3.10.4
// - protoc              v5.29.2
// source: test.proto

package helloworld

import (
	context "context"
	proto "go.unistack.org/micro-tests/client/grpc/proto"
	client "go.unistack.org/micro/v3/client"
	metadata "go.unistack.org/micro/v3/metadata"
)

var (
	TestName = "Test"
)

type TestClient interface {
	Call(ctx context.Context, req *proto.Request, opts ...client.CallOption) (*proto.Response, error)
	Stream(ctx context.Context, opts ...client.CallOption) (Test_StreamClient, error)
}

type Test_StreamClient interface {
	Context() context.Context
	SendMsg(msg interface{}) error
	RecvMsg(msg interface{}) error
	CloseAndRecv() (*proto.Response, error)
	CloseSend() error
	Close() error
	Header() metadata.Metadata
	Send(msg *proto.Request) error
	Recv() (*proto.Response, error)
}

type TestServer interface {
	Call(ctx context.Context, req *proto.Request, rsp *proto.Response) error
	Stream(ctx context.Context, stream Test_StreamStream) error
}

type Test_StreamStream interface {
	Context() context.Context
	SendMsg(msg interface{}) error
	RecvMsg(msg interface{}) error
	SendAndClose(msg *proto.Response) error
	Close() error
	Recv() (*proto.Request, error)
	Send(msg *proto.Response) error
}
