// Code generated by protoc-gen-go-micro. DO NOT EDIT.
// protoc-gen-go-micro version: v3.10.1
// source: test.proto

package pb

import (
	context "context"
	v3 "go.unistack.org/micro-client-http/v3"
	v31 "go.unistack.org/micro-server-http/v3"
	proto "go.unistack.org/micro-tests/server/combo/proto"
	client "go.unistack.org/micro/v3/client"
	server "go.unistack.org/micro/v3/server"
	http "net/http"
	time "time"
)

type testClient struct {
	c    client.Client
	name string
}

func NewTestClient(name string, c client.Client) TestClient {
	return &testClient{c: c, name: name}
}

func (c *testClient) Call(ctx context.Context, req *proto.CallReq, opts ...client.CallOption) (*proto.CallRsp, error) {
	errmap := make(map[string]interface{}, 1)
	errmap["default"] = &proto.Error{}
	opts = append(opts,
		v3.ErrorMap(errmap),
	)
	opts = append(opts,
		v3.Method(http.MethodPost),
		v3.Path("/v1/call"),
		v3.Body("*"),
	)
	td := time.Duration(5000000000)
	opts = append(opts, client.WithRequestTimeout(td))
	rsp := &proto.CallRsp{}
	err := c.c.Call(ctx, c.c.NewRequest(c.name, "Test.Call", req), rsp, opts...)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

type testServer struct {
	TestServer
}

func (h *testServer) Call(ctx context.Context, req *proto.CallReq, rsp *proto.CallRsp) error {
	var cancel context.CancelFunc
	td := time.Duration(5000000000)
	ctx, cancel = context.WithTimeout(ctx, td)
	defer cancel()
	return h.TestServer.Call(ctx, req, rsp)
}

func RegisterTestServer(s server.Server, sh TestServer, opts ...server.HandlerOption) error {
	type test interface {
		Call(ctx context.Context, req *proto.CallReq, rsp *proto.CallRsp) error
	}
	type Test struct {
		test
	}
	h := &testServer{sh}
	var nopts []server.HandlerOption
	nopts = append(nopts, v31.HandlerEndpoints(TestServerEndpoints))
	return s.Handle(s.NewHandler(&Test{h}, append(nopts, opts...)...))
}
