// Code generated by protoc-gen-micro
// source: github.proto
package pb

import (
	context "context"
	api "github.com/unistack-org/micro/v3/api"
	client "github.com/unistack-org/micro/v3/client"
)

func NewGithubEndpoints() []*api.Endpoint {
	return []*api.Endpoint{
		&api.Endpoint{
			Name:    "Github.LookupUser",
			Path:    []string{"/users/{username}"},
			Method:  []string{"GET"},
			Handler: "rpc",
		},
	}
}

type GithubClient interface {
	LookupUser(ctx context.Context, req *LookupUserReq, opts ...client.CallOption) (*LookupUserRsp, error)
}

type GithubServer interface {
	LookupUser(ctx context.Context, req *LookupUserReq, rsp *LookupUserRsp) error
}
